/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_ndk_NdkSimple3 */

#ifndef _Included_jni_demo_com_parcel
#define _Included_jni_demo_com_parcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_ndk_NdkSimple3
 * Method:    callStaticMethod
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_jni_demo_com_parcel_nativeCreate
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_jni_demo_com_parcel_nativeWriteInt
        (JNIEnv *, jobject, jlong, jint);

JNIEXPORT jint JNICALL Java_jni_demo_com_parcel_nativeReadInt
        (JNIEnv *, jobject, jlong);

JNIEXPORT void JNICALL Java_jni_demo_com_parcel_nativeSetDataPosition
        (JNIEnv *, jobject, jlong, jint);
#ifdef __cplusplus
}
#endif
#endif
